config/routes.rb
Rails.application.routes.draw do
  devise_for :app_users

  devise_scope :app_user do
    get "/app_users/sign_out" => "devise/sessions#destroy"
  end
  
  get 'place_order/order'
  get 'add_items/items'

  resources :deal_deal_items
  resources :order_order_details
  resources :menu_item_carts
  resources :menu_item_addons

  root 'welcome#index'
  get 'dashboard/display'
  get '/search', to: 'search#search', as: 'search'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  
  # Defines the root path route ("/")
  # root "articles#index"

  # devise_scope :app_user do
  #   get 'signup', to: 'app_users/registrations#new', as: :app_user_registration
  #   post 'signup', to: 'app_users/registrations#create', as: :app_user_registration
  # end
  
end

app/models/addon.rb
class Addon < ApplicationRecord
    has_many :menu_item_addons
    has_many :menu_items, through: :menu_item_addons
end

app/models/admin.rb
class Admin < ApplicationRecord
    # has_one :app_user, as: :user
    # belongs_to :user,
    # class_name: 'AppUser', foreign_key: 'app_user_id', polymorphic: true
    has_one :app_user, as: :user
end 

app/models/app_user.rb
class AppUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  belongs_to :user, polymorphic: true
  # has_one :customer, dependent: :destroy, inverse_of: :app_user
  # accepts_nested_attributes_for :customer

  # has_one :admin, as: :user
  # has_one :manager, as: :user
  # has_one :customer, as: :user

  validates :email, presence: true, format: { with: /\A[^@\s]+@[^@\s]+\z/, message: "Please enter a valid email address."}
  validates :first_name, presence:true
  validates :last_name, presence:true
  validates :password, presence:true
  validates :phone_no, presence:true
  validates :address, presence:true
  
end

app/models/cart.rb
class Cart < ApplicationRecord
    has_many :menu_item_carts
    has_many :menu_items, through: :menu_item_carts
    belongs_to :customers
end

app/models/customer.rb
class Customer < ApplicationRecord
    has_many :orders
    has_one :cart
    has_one :app_user, as: :user
    #belongs_to :user, polymorphic: true, inverse_of: :customer
    
end

app/models/deal.rb
class Deal < ApplicationRecord
    belongs_to :manager
    has_many :deal_deal_items
    has_many :deal_items, thouugh: :deal_deal_items
end

app/models/deal_deal_item.rb
class DealDealItem < ApplicationRecord
  belongs_to :deal
  belongs_to :deal_item
end

app/models/deal_item.rb
class DealItem < ApplicationRecord
    belongs_to :menu_item
    has_many :deal_deal_items
    has_many :deal, thouugh: :deal_deal_items
end

app/models/discount.rb
class Discount < ApplicationRecord
  belongs_to :discountable, polymorphic: true
end

app/models/manager.rb
class Manager < ApplicationRecord
    belongs_to :restaurant
    has_many :menu_items
    has_many :deals
    has_one :app_user, as: :user
    
end

app/models/menu_category.rb
class MenuCategory < ApplicationRecord
    has_many :menu_items
end

app/models/menu_item.rb
class MenuItem < ApplicationRecord
    belongs_to :menu_category
    belongs_to :manager
    has_one :deal_item
    has_one :order_detail
    has_many :menu_item_addons
    has_many :addons, through: :menu_item_addons
    has_many :menu_item_carts
    has_many :carts, through: :menu_item_carts
    has_one :discount, as: :discountable
end

app/models/menu_item_addon.rb
class MenuItemAddon < ApplicationRecord
  belongs_to :menu_item
  belongs_to :addon
end

app/models/menu_item_cart.rb
class MenuItemCart < ApplicationRecord
  belongs_to :menu_item
  belongs_to :cart
end

app/models/order.rb
class Order < ApplicationRecord
    belongs_to :customer
    has_one :payment
    has_many :order_order_details
    has_many :order_details, through: :order_order_details
    has_one :discount, as: :discountable
end

app/models/order_detail.rb
class OrderDetail < ApplicationRecord
    belongs_to :menu_item
    has_many :order_order_details
    has_many :orders, through: :order_order_details
    has_one :discount, as: :discountable
end

app/models/payment.rb
class Payment < ApplicationRecord
    belongs_to :orders
    belongs_to :payment_methods
end

app/models/payment_method.rb
class PaymentMethod < ApplicationRecord
    has_one :payment
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
    has_many :managers
end

app/controllers/add_items_controller.rb
class AddItemsController < ApplicationController
  def items
  end
end

app/helpers/add_items_helper.rb
module AddItemsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/add_items/items.html.erb
<h3>Add Items</h3>

<body style="margin-left: 30px;">
    <div class="row">
    <div class="col-md-3">
    <label for="formFile" class="form-label">Item Name</label>
        <input type="text" class="form-control" placeholder="Item name" aria-label="Item Name">
    </div>
    <div class="col-md-3">
    <label for="formFile" class="form-label">Restaurant</label>
        <input type="text" class="form-control" placeholder="Restaurant" aria-label="Restaurant">
    </div>
    </div>

    <div class="row">
        <div class="col-md-3">
            <label for="formFile" class="form-label">Add Image</label>
            <input class="form-control" type="file" id="formFile">
        </div>
        <div class="col-md-3">
            <label for="formFile" class="form-label">Price</label>
            <input type="text" class="form-control" placeholder="Price" aria-label="Last name">
        </div>
    </div>

        <div class="col-md-6">
            <label for="formFile" class="form-label">Category</label>
            <div class="input-group mb-3">
                <select class="form-select" id="inputGroupSelect02">
                    <option selected>Choose...</option>
                    <option value="1">Shake</option>
                    <option value="2">Pizza</option>
                    <option value="3">Burger</option>
                </select>
            </div>
        </div>

    <%= link_to 'Add to Menu', add_items_items_path, class: 'btn btn-white shadow-warning text-warning' %>

</body>